# import = ["/Users/martin/.config/alacritty/themes/github_light_high_contrast.toml"]

import = [
  # "/Users/martin/.config/alacritty/themes/gruvbox_material_medium_light.toml",
    "/Users/martin/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
    #"/Users/martin/.config/alacritty/themes/solarized_dark.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Regular"

[window]

[window.dimensions]
columns = 120
lines = 80

# split tmux window vertically
[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

# split tmux window horizontally
[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

# create a new tmux window
[[keyboard.bindings]]
chars = "\u0002c"
key = "C"
mods = "Command"

#switch to next tmux window
[[keyboard.bindings]]
chars = "\u0002n"
key = "]"
mods = "Command"

#switch to previous tmux window
# TODO: fix "Grave"
[[keyboard.bindings]]
chars = "\u0002p"
key = "["
mods = "Command"

# # switch to pane left
# [[keyboard.bindings]]
# chars = "\u0002h"
# key = "h"
# mods = "Command"

# switch to pane right
[[keyboard.bindings]]
chars = "\u0002l"
key = "l"
mods = "Command"

# switch to pane up
[[keyboard.bindings]]
chars = "\u0002k"
key = "k"
mods = "Command"

# switch to pane down
[[keyboard.bindings]]
chars = "\u0002j"
key = "j"
mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002 "
# key = "C"
# mods = "Command|Shift"


# [[keyboard.bindings]]
# chars = """
# :Grep
# """
# key = "F"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002[/"
# key = "F"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002g"
# key = "G"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002G"
# key = "G"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002T"
# key = "J"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002T"
# key = "K"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002L"
# key = "L"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002u"
# key = "O"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# :GoToFile
# """
# key = "P"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# :GoToCommand
# """
# key = "P"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = """
# :q
# """
# key = "Q"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# \u001B:w
# """
# key = "S"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# \u001B:wq
# """
# key = "S"
# mods = "Command|Shift"


# [[keyboard.bindings]]
# chars = "\u0002]"
# key = "V"
# mods = "Command|Shift"


# [[keyboard.bindings]]
# chars = "\u0002P"
# key = "T"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002x"
# key = "W"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002z"
# key = "Z"
# mods = "Command"


# [[keyboard.bindings]]
# chars = "\u0002,"
# key = "Comma"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# :ZenMode
# """
# key = "Period"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u000F"
# key = "LBracket"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "LBracket"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\t"
# key = "RBracket"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002n"
# key = "RBracket"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002:"
# key = "Semicolon"
# mods = "Command"

# Map numbers. Use cmd +[0-9] to move through tmux windows
[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"
