[gcloud]
detect_env_vars = ["CLOUDSDK_CONFIG"]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[nodejs]
disabled = true

[package]
disabled = true

[shell]
disabled = false

[golang]
disabled = true
